# Generated by Django 5.1.3 on 2024-11-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='admissionNumber',
            field=models.IntegerField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
