# Generated by Django 5.0.7 on 2024-11-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='admissionNumber',
            field=models.IntegerField(),
        ),
    ]
