# Generated by Django 5.0.7 on 2024-11-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
